services:
  nickname-svc:
    build:
      context: .
    environment:
      OTEL_SERVICE_NAME: "nickname-svc"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    ports:
      - "127.0.0.1:8081:8081"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgrespassword
    restart: always
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.40.1.cli-migrations-v3
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./hasura:/var/schema
    environment:
      NICKNAME_SERVICE: "http://nickname-svc:8081"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 60
      HASURA_GRAPHQL_PRO_KEY: ${HASURA_GRAPHQL_PRO_KEY}
      HASURA_GRAPHQL_MIGRATIONS_DIR: "/var/schema/migrations"
      HASURA_GRAPHQL_METADATA_DIR: "/var/schema/metadata"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, query-log, http-log, webhook-log
      HASURA_GRAPHQL_ENABLED_APIS: metadata,graphql,config,metrics
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "naming_convention"
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
      HASURA_FF_NAMING_CONVENTION_SEP_2023: "True"

  # All traces and metrics from Go and Hasura will first go into the
  # OpenTelemetry Collector.
  collector:
    image: otel/opentelemetry-collector
    expose:
      - 4317 # otlp grpc
      - 4318 # otlp http
    ports:
      - "127.0.0.1:4317:4317" # otlp grpc
      - "127.0.0.1:4318:4318" # otlp http
    volumes:
      - ./otel-config.yml:/etc/otel-config.yaml
    command: "--config=/etc/otel-config.yaml"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.57
    # Enable OTLP export of traces from OTel Collector to Jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    # Expose Jaeger's OTLP ports so the OTel Collector can write to Jaeger
    expose:
      - 4317 # otlp grpc
      - 4318 # otlp http
      - 14269 # jaeger collector, admin port
      - 5778 # serves sampling strategies
    ports:
      - "127.0.0.1:16686:16686" # jaeger ui

volumes:
  pg_data:
